---
driver_plugin: vagrant
driver_config:
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 443, host: 8443}]
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: debian-7.4
  driver_config:
    box: opscode-debian-7.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
  run_list:
  - recipe[yum-epel]

suites:
- name: boxbilling3
  run_list: ["recipe[boxbilling_test]"]
  attributes:
    boxbilling:
      download_url: http://mirror.onddo.com/boxbilling-3.6.11.zip
- name: boxbilling4
  run_list: ["recipe[boxbilling_test]"]
  attributes:
    boxbilling:
      download_url: https://github.com/boxbilling/boxbilling/releases/download/4.11.11/BoxBilling.zip
