---
driver:
  name: vagrant
  vm_hostname: "boxbilling.local"
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-6.6
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.6
  run_list: ["recipe[apt]"]
- name: fedora-19
- name: fedora-20
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.10
  run_list: ["recipe[apt]"]

suites:
- name: boxbilling3
  run_list: ["recipe[boxbilling_test]"]
  attributes:
    boxbilling:
      download_url: http://mirror.onddo.com/boxbilling-3.6.11.zip
- name: boxbilling4
  run_list: ["recipe[boxbilling_test]"]
  attributes:
    boxbilling:
      download_url: https://github.com/boxbilling/boxbilling/releases/download/4.12.1/BoxBilling.zip
